name: Auto Update Publications from Google Scholar

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install scholarly
        run: pip install scholarly

      - name: Run script to generate Markdown publications
        run: python update_publications.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: auto-update publications from Google Scholar'
          title: 'Auto Update Publications'
          body: |
            This PR updates the `content/publication/` folder using your latest Google Scholar publications.
          base: main
          branch: auto/update-publications
          delete-branch: true

